const QUANTITY_PICTURES = 25;
const MAX_ID_COMMENT = 500;
const MIN_LIKES = 15;
const MAX_LIKES = 200;
const MIN_COMMENT = 0;
const MAX_COMMENT = 30;

export {QUANTITY_PICTURES, MAX_ID_COMMENT, MIN_LIKES, MAX_LIKES, MIN_COMMENT, MAX_COMMENT};
